# Generated by Django 3.2 on 2021-04-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentset',
            name='producer_id',
            field=models.IntegerField(default=None),
        ),
    ]
