# Generated by Django 3.2 on 2021-04-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_electronicapplication_electronicapplicationdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ElectronicApplication',
        ),
        migrations.DeleteModel(
            name='ElectronicApplicationDocument',
        ),
    ]
