# Generated by Django 3.2 on 2021-04-24 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20210424_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentset',
            name='name',
            field=models.CharField(default=None, max_length=256),
            preserve_default=False,
        ),
    ]
