# Generated by Django 3.2 on 2021-04-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentset_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentset',
            name='description',
            field=models.CharField(max_length=4096),
        ),
    ]
