# Generated by Django 3.2 on 2021-04-24 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectronicApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_set_id', models.IntegerField()),
                ('completed_date', models.DateField(default=datetime.datetime.now)),
                ('consumer_id', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=128)),
            ],
        ),
    ]
