# Generated by Django 3.2 on 2021-04-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronic_app', '0002_alter_electronicapplication_consumer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicapplication',
            name='consumer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
